"""Add new column and remove old column

Revision ID: ca96b88181fa
Revises: 
Create Date: 2024-12-28 00:13:06.029028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca96b88181fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encrypted_file_shares', sa.Column('file_metadata', sa.JSON(), nullable=False))
    op.alter_column('files', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'user_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('encrypted_file_shares', 'file_metadata')
    # ### end Alembic commands ###
